### ISSUE TITLE
CMakeLists.txt wrong 

### ISSUE THREAD

**Issue by nanu-c** [ubports/media-hub#1]
there is a duplicate check
https://github.com/ubports/media-hub/blob/738579e71016622ed6e87c0847f0eb290bdb8dc2/CMakeLists.txt#L52
and it's missing 
```
/usr/bin/ld: cannot find -lhybris-common
collect2: error: ld returned 1 exit status
```
so should add libhybris-common to pkg_check_modules

**Comment by mardy** [comment]
This should have been fixed last summer (please reopen if that's not the case)
