### ISSUE TITLE
Media Hub doesn't play any audio after a stream fails to play

### ISSUE THREAD

**Issue by cibersheep** [ubports/media-hub#12]
- Test a failing audio from Music App (see audio attached, uncompress and import in Music) or Flas (look for station name Air1)
- Try to play other audio (other song in Music App or other stream in Flas)

Audio doesn't play until app is restarted.

http://paste.ubuntu.com/p/F6HTG3GbSK/ from line 34

Tested on Arale dev channel

[failingaudio.zip](https://github.com/ubports/media-hub/files/5125847/failingaudio.zip)

**Comment by UniversalSuperBox** [comment]
This repository has moved to GitLab. You may find this request on GitLab at the following URL:

https://gitlab.com/ubports/core/media-hub/-/issues/57
