### ISSUE TITLE
Cannot seek before playing

### ISSUE THREAD

**Issue by mardy** [ubports/media-hub#14]
QtMultimedia allows seeking into a video which is not in playing state (this works on the Linux desktop, at least).

However, this fails in media-hub, because the call to `gst_element_seek_simple()` in [gstreamer/playbin.cpp](https://github.com/ubports/media-hub/blob/xenial/src/core/media/gstreamer/playbin.cpp#L689) returns false.This might be fixed by setting the pipeline to PAUSED state (if the media was not playing already).

**Comment by UniversalSuperBox** [comment]
This repository has moved to GitLab. You may find this request on GitLab at the following URL:

https://gitlab.com/ubports/core/media-hub/-/issues/14
