### ISSUE TITLE
Media playback should be paused while buffering

### ISSUE THREAD

**Issue by mardy** [ubports/media-hub#16]
According to the [GStreamer playbin documentation](https://gstreamer.freedesktop.org/documentation/playback/playbin.html?gi-language=c#buffering), playback should be paused while the buffering value is less than 100.

It has been reported [in the forum](https://forums.ubports.com/post/40640) that while buffering the stream continues to play, causing a jump in the contents.

**Comment by cibersheep** [comment]
I think this issue is already here: https://github.com/ubports/media-hub/issues/11

**Comment by dano6** [comment]
I discovered that https://api-docs.ubports.com/sdk/apps/qml/QtMultimedia/MediaPlayer.html?highlight=mediaplayer#sdk-qtmultimedia-mediaplayer-status wasn't switching to Buffering state. I wanted make workaround for this issue in qml but it was impossible

**Comment by mardy** [comment]
> I think this issue is already here: #11

Technically, they are not the same: the issue you link is about reporting the buffering state (which, if I'm not mistaken, is already happening, and it may be that `qtubuntu-media` is just not propagating the message to the client -- but I need to double-check), whereas this one is about stopping the stream in media-hub's `Playbin` class.

**Comment by UniversalSuperBox** [comment]
This repository has moved to GitLab. You may find this request on GitLab at the following URL:

https://gitlab.com/ubports/core/media-hub/-/issues/16
