### ISSUE TITLE
AppArmor prevents playing audio files from temp dir

### ISSUE THREAD

**Issue by jonnius** [ubports/media-hub#2]
- Device: FP2
- Channel: dev
- Build: 2019-08-21/2

### Steps to reproduce
Develop an app that tries to play audio files from app's temp dir or use [this Pure Maps branch](https://github.com/jonnius/pure-maps/tree/tmpaudiobug). See [README](https://github.com/jonnius/pure-maps/tree/tmpaudiobug) on how to build the app. In the app go to Settings -> Test to test TTS.

### Expected behavior
Sound can be played when file is located at temp dir.

### Actual behavior
AppArmor prevents app to play sound to be played when file is located at temp dir (`e.g. /run/user/32011/confined/pure-maps.jonius/pure-maps-nkz88va5/tmpma4imrj5.wav`). 

App is even allowed to create that file, but not to play it. When using another location like the app cache, this issue does not occur.

### Logfiles and additional information
[error.log](https://github.com/ubports/ubuntu-touch/files/3537938/error.log)
relevant line from log:
```
mpris.Player.Error.InsufficientAppArmorPermissions: Warning: Failed to authenticate necessary apparmor permissions to open uri: Client is not allowed to access: file:///run/user/32011/confined/pure-maps.jonius/pure-maps-nkz88va5/tmpma4imrj5.wav
```

This issue even occurs when making app unconfined.

**Comment by dobey** [comment]
There is no actual denial logged. It is a problem with the permissions check from within media-hub, when the playback of the file is requested.

**Comment by jonnius** [comment]
I can't see the denial in the [syslog.txt](https://github.com/ubports/media-hub/files/3563516/syslog.txt). 

In the [media-hub.log](https://github.com/ubports/media-hub/files/3563531/media-hub.log) there is the same warning: 
```
[EE 2019-09-01 13:26:26.483720] [player_skeleton.cpp:213@operator()] Warning: Failed to authenticate necessary apparmor permissions to open uri: Client is not allowed to access: file:///run/user/32011/confined/pure-maps.jonnius/pure-maps-zwup08xc/tmpdj7kud92.wav
```

**Comment by lduboeuf** [comment]
is there any progress on it ? I'm facing the same issue

**Comment by jonnius** [comment]
I don't think so. In Pure Maps we worked around this by putting the files into the app cache directory.

**Comment by lduboeuf** [comment]
well , not sure how i can handle that, the Audio source file is a "qrc:/...." file from the app cache directory already
[Edit]: Or i need to extract the audio from the qrc before...
