### ISSUE TITLE
Ringtones don't work anymore

### ISSUE THREAD

**Issue by fredldotme** [ubports/media-hub#20]
Description:
Since the recent merge of the remotemedia branch into xenial media-hub fails to play back ringtones.

Steps to reproduce:
- Upgrade to devel
- Select a ringtone from the ringtones list in system-settings

Expected behavior:
- Ringtone plays back

Actual behavior:
- Ringtone fails to play back

Steps to get back to a working state:
```
sudo mount -o remount,rw /
sudo apt update
sudo apt install media-hub=4.6.2+0ubports1+0~20201010065504.5~1.gbp9d51fe
sudo apt install libmedia-hub-client5=4.6.2+0ubports1+0~20201010065504.5~1.gbp9d51fe
sudo apt install libmedia-hub-common5=4.6.2+0ubports1+0~20201010065504.5~1.gbp9d51fe
sudo reboot
```

**Comment by dano6** [comment]
I found similar regression in Podbird: 

- play some episode
- close podbird
- open podbird
- click play to continue in playing episode
     

Expected behavior:
- episode continue playing
     

Actual behavior:
- nothing happens
- to fix press pause and press play again

**Comment by UniversalSuperBox** [comment]
This seems no longer relevant
