### ISSUE TITLE
Display is woken up when playback starts with display off

### ISSUE THREAD

**Issue by mardy** [ubports/media-hub#30]
1. Open the Gallery
2. Tap a video for playback
3. Tap the Play button so the media-player app starts
4. Lock the screen before the media-player app loads

After a few seconds, the screen turns back on and video playback begins behind the lock screen.

**Comment by UniversalSuperBox** [comment]
This repository has moved to GitLab. You may find this request on GitLab at the following URL:

https://gitlab.com/ubports/core/media-hub/-/issues/30
