### ISSUE TITLE
Endless loop while trying to play a song on cloud music 

### ISSUE THREAD

**Issue by lduboeuf** [ubports/media-hub#37]
logs: 
http://paste.ubuntu.com/p/NBvWdPNctX/
http://paste.ubuntu.com/p/TZyrp8mPYx/

**Comment by mardy** [comment]
Hi Lionel! The logs show that media-hub could not access the remote resource (the songs are just not there, the page returns a 404), so maybe after trying to play all of them (and failing) it loops back to the only one song that works?

edit: or is the problem that no song works, and that media-hub just keeps trying forever? If the latter, I think that the behaviour is correct: it should be the application's responsibility to react on the error and stop the looping.

**Comment by lduboeuf** [comment]
Well the app was working before, so idk if something need to be done on media-hub or if the app need adaptation

**Comment by lduboeuf** [comment]
reported here: https://gitlab.com/johangm90/cloudmusic-qml/-/issues/21

**Comment by lduboeuf** [comment]
it seems not the case anymore on RC
