### ISSUE TITLE
Playing two things at the same time causes the device to stop sleeping

### ISSUE THREAD

**Issue by UniversalSuperBox** [ubports/media-hub#41]
When two separate players are created, played, and stopped in rapid succession, the media-hub service requests two system wakelocks from repowerd, one for each player. Repowerd happily issues, say, IDs 9 and 10. When the players clear, media-hub clears wakelock ID 10 twice. This leaves ID 9 dangling, so the device never goes into deep sleep.

This can happen, for example, when Lomiri starts with an SD card with two invalid partitions on it inserted. Nuntium fires two notifications at almost exactly the same time, they both play their audio at almost the same time, and the condition is triggered.

**Comment by Danfro** [comment]
Not sure if this is the best way of testing, but I tried to
1. open music app, start playing a song
2. open gallery app and play a video (opens in media player app)

I can not make both playing at the same time. If I start the video, the song stops playing. If I start the song again, the video stops playing. And the device goes to sleep after the set amount of time after that.

Xperia X, devel, 64bit

**Comment by Flohack74** [comment]
@danfro it should be easy to do this, if you are able to receive a notification during audio playback of some piece of music maybe.

**Comment by Danfro** [comment]
Ok, I got music playing. Then 1. send myself an email to force a notification sound and 2. set a timer to trigger an alarm. 

The device went to sleep after the set time.

**Comment by ivoxavier** [comment]
FP2;N5 and 6T as Danfro, so OK for me as well.
