### ISSUE TITLE
Music keeps playing even when Music app is closed

### ISSUE THREAD

**Issue by c4pp4** [ubports/media-hub#48]
- Device: Xiaomi Mi A2, Sony Xperia X
- Channel: any
- Build: any

### Steps to reproduce
open Music app
Queue as many songs as possible (the limit is changing, sometimes it's 700+ songs, sometimes 400+, it's weird)
play music from Queue (at least half of track)
close Music app

### Expected behavior
music stops playing

### Actual behavior
music keeps playing
when the Music app is started again its state is with triangle icon at right bottom (so music should not be playing) but the music started before the closing app is still playing in the background.

**Comment by Flohack74** [comment]
@mardy is this a regression to the latest changes we did?

**Comment by c4pp4** [comment]
> @mardy is this a regression to the latest changes we did?

I just want to note it behaves the same way on OTA 18.

**Comment by UniversalSuperBox** [comment]
This repository has moved to GitLab. You may find this request on GitLab at the following URL:

https://gitlab.com/ubports/core/media-hub/-/issues/48
