### ISSUE TITLE
shuffle and repeat do conflict

### ISSUE THREAD

**Issue by Danfro** [ubports/media-hub#51]
As the result of my testing, in music app (not sure about other apps) shuffle seems to disable repeat action. Which I think is not what it should do in all cases.

To reproduce:
- set repeat to repeat album
- enable shuffle
expected: songs are played randomly, when all have been played once, it does start again
actual behaviour: if all songs are played, the music stops

- set repeat to repeat single song
- enable shuffle
expected: the selected song keeps being played (in my opinion this should be overriding shuffle)
actual behaviour: shuffle keeps playing random songs from the album

I think 
- when shuffle is enabled and repeat album is set, the album should be kept playing in random order "endless" (due to repeat)
- when shuffle is enabled and repeat single song is set, the selected song should be played "endless"

@mardy this is with the old media hub, it has got nothing to do with #50 .

**Comment by mardy** [comment]
Hi!

How do you actually set the repeat mode to "single song"? When I change it in music app, it only switches between "None" and "Playlist" -- I found no way to set the loop to a single song.

About playlist shuffle, this now should work fine with the latest update I pushed to the `xenial_-_mediahubqt` repository, in the sense that when the playlist ends, it continues playing from the start.

This, however, is different from the desired behaviour that was voted in our telegram QA group, where most participants want to issue a new shuffling of the list before playing the second loop. I'll work on that :-)

**Comment by Danfro** [comment]
@mardy repeat single is only available via my open MR for music app [#61](https://gitlab.com/ubports/apps/music-app/-/merge_requests/61). I think I mentioned that in the Telegram chat but forgot to add it to this issue here.

Thanks for working on this. :+1:
