### ISSUE TITLE
[feature request] complete scrolling of the title of a piece of music

### ISSUE THREAD

**Issue by gbdomubpkm** [ubports/media-hub#55]
![screenshot20220107_144042663](https://user-images.githubusercontent.com/50362604/148636456-55dfe64e-e3bb-4f27-a154-e663a2d3f381.png)
It is not possible to see the entirety of a long title of a piece of music through the sound drop-down menu of the indicator bar when using Patrick Jane's Radio app, for example : currently, display frozen on a certain maximum number of characters.

Would it be possible to implement a complete scrolling of the title? Thanks

**Comment by UniversalSuperBox** [comment]
This repository has moved to GitLab. You may find this request on GitLab at the following URL:

https://gitlab.com/ubports/core/media-hub/-/issues
