### ISSUE TITLE
unreachable code

### ISSUE THREAD

**Issue by maddin200** [ubports/media-hub#56]
/tests/lib/functional/dbusmock.h line 57

Code:
case QDBusArgument::StructureType: {
		value.beginStructure();
		QVariantList list;
		while (!value.atEnd()) {
			list << value.asVariant();
		}
		value.endStructure();
		return list;
		break; // <-- unreachable

**Comment by Flohack74** [comment]
Well how about you create a PR to remove this line? :)

**Comment by maddin200** [comment]
voila - https://github.com/ubports/media-hub/pull/57
