### ISSUE TITLE
lookup or default image for album art is not working

### ISSUE THREAD

**Issue by wdehoog** [ubports/media-hub#6]
Two issues with album art:

- The default image to use in case of missing album art does not exist anymore.

- The 'dash image proxy', whatever it was, does not exist anymore.

The result is there is no default album art image shown in the sound indicator.

Not a very big problem I admit.

**Comment by UniversalSuperBox** [comment]
Fixed by https://github.com/ubports/media-hub/pull/7

**Comment by jezek** [comment]
Device: FP2
OS: 2020-W43

- playing song with album art - the album art is showing in sound indicator.
- playing song without album art - a musical note :musical_note: pictogram is showing in sound indicator
