### ISSUE TITLE
use embedded abum art for audio streams

### ISSUE THREAD

**Issue by wdehoog** [ubports/media-hub#9]
media-hub relies on thumbnailer to fetch album art. This only works for local files.
Audio streams (for example from a dlna server) can contain embedded album art. Gstreamer can handle it so media-hub should be able to support them.

**Comment by UniversalSuperBox** [comment]
This repository has moved to GitLab. You may find this request on GitLab at the following URL:

https://gitlab.com/ubports/core/media-hub/-/issues/9
